# ++
# Copyright 2004-2007 Joyent Inc.
# 
# Redistribution and/or modification of this code is 
# governed by the GPLv2.
# 
# Report issues and contribute at http://dev.joyent.com/
# 
# $Id$
# --

development:
  system: imap
  host:   hostname
  port:   143

test:
  system: static
  host:     hostname
  port:     143

production:
  system: static
  host:     hostname
  port:     143
